/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__ */

#ifndef _Included_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
#define _Included_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_play
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_stop
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_pause
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_resume
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_next
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    previous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_previous
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_release
  (JNIEnv *, jobject);

/*
 * Class:     info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative__
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT int JNICALL Java_info_acidflow_homer_modules_music_deezer_jni_DeezerPlayerNative_00024_changeVolume
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
